[project]
name = "projeto-redes-neurais"
version = "0.1.0"
description = "Pipeline MLP do zero em PyTorch para classificacao de especies, dataset Palmer Penguins"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kagglehub>=1.0.2",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "tensorboard>=2.21.0",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
]
